#!/bin/bash

pathregex="(\s|^)((/|)[a-zA-Z0-9.]+)(/[a-zA-Z0-9.]+)+"

filepaths=""
for i in $(grep -aEo "$pathregex" | sed "s/\s//g"); do
  [[ -e "$i" ]] && filepaths+="$i$IFS"
done
filepaths=${filepaths%$IFS}
[ -z "$filepaths" ] && exit 1

while getopts "hoc" o; do case "${o}" in
	h) printf "Optional arguments for custom use:\\n  -c: copy\\n  -o: xdg-open\\n  -h: Show this message\\n" && exit 1 ;;
	o) chosen="$(echo "$filepaths" | sed "s/\s//g" | dmenu -i -p 'Open which filepath?' -l 10)"
	st -e lfimg "$chosen" ;;
	c) echo "$filepaths" | sed "s/\s//g" | dmenu -i -p 'Copy which filepath?' -l 10 | tr -d '\n' | xclip -selection clipboard ;;
	*) printf "Invalid option: -%s\\n" "$OPTARG" && exit 1 ;;
esac done
